-- review-service, migration 1: the messaging spine.
--
-- outbox_event: events written in the SAME transaction as the change that
-- caused them, and moved out later by the relay. This is the fix for the push
-- service's "save, then queue.add()" order, which loses work when Redis fails
-- between the two.
--
-- inbox_event: events already handled, keyed (source, event_id). Every
-- consumer writes this row first, so a redelivered event finds it and does
-- nothing.
--
-- Every statement is retry-safe (IF NOT EXISTS), so a migration interrupted
-- half way can simply be run again.

-- ─── generated by prisma migrate diff ──────────────────────────────────────

CREATE TABLE IF NOT EXISTS "outbox_event" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "aggregate_type" TEXT NOT NULL,
    "aggregate_id" UUID NOT NULL,
    "event_type" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "published_at" TIMESTAMPTZ(6),
    "attempts" SMALLINT NOT NULL DEFAULT 0,
    "last_error" TEXT,
    "next_attempt_at" TIMESTAMPTZ(6),

    CONSTRAINT "outbox_event_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "inbox_event" (
    "source" TEXT NOT NULL,
    "event_id" TEXT NOT NULL,
    "event_type" TEXT NOT NULL,
    "tenant_id" UUID,
    "outcome" TEXT NOT NULL,
    "received_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "inbox_event_pkey" PRIMARY KEY ("source","event_id")
);

CREATE INDEX IF NOT EXISTS "outbox_event_aggregate_idx"
    ON "outbox_event"("aggregate_type", "aggregate_id");

-- ─── hand-written: what Prisma cannot express ─────────────────────────────

-- THE RELAY'S CLAIM INDEX, PARTIAL. The relay polls "unpublished, oldest
-- first" every second, forever. Published rows are the overwhelming majority
-- and are never read again by the relay, so they stay out of the index:
-- unpredicated, it would grow with every event ever sent.
CREATE INDEX IF NOT EXISTS "outbox_event_unpublished_idx"
    ON "outbox_event"("created_at")
    WHERE "published_at" IS NULL;

-- Sanity on the delivery bookkeeping.
DO $$ BEGIN
    ALTER TABLE "outbox_event"
        ADD CONSTRAINT "outbox_event_attempts_non_negative" CHECK ("attempts" >= 0);
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    ALTER TABLE "inbox_event"
        ADD CONSTRAINT "inbox_event_ids_not_blank"
        CHECK (btrim("source") <> '' AND btrim("event_id") <> '');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
