-- review-service, migration 2: reviews, invites, replies, reports, and the
-- stored rating summary.
--
-- Ported from gostyle-platform 20260807120000_storefront_reviews_spine and
-- 20260808120000_storefront_review_replies_reports, with three changes:
--
--   1. booking_source JOINS EVERY BOOKING KEY. Two systems mint booking ids
--      now (gostyle-platform and gostyle-booking-api), and a key should say
--      which system an id belongs to. UNIQUE (booking_source, booking_id) on
--      review and on review_invite.
--   2. CHECK constraints back the domain rules. The platform left the rating
--      CHECK out so every message came from the domain; the domain still
--      writes every message, and these are the backstop in a database no
--      other code shares.
--   3. The rating summary is STORED (rating_summary). customer-api cannot run
--      the platform's query across a service boundary. It is written in the
--      same transaction as each review change and recomputed nightly.
--
-- NO FOREIGN KEYS to other services' ids (tenant, storefront, branch, booking,
-- customer, staff). The only foreign keys are between this service's tables.
--
-- Enum type names are SUFFIXED (review_state, not review): Postgres keeps
-- tables and types in one namespace.
--
-- Every statement is retry-safe.

-- ─── generated by prisma migrate diff, made retry-safe ────────────────────

DO $$ BEGIN
    CREATE TYPE "booking_source" AS ENUM ('platform', 'booking_api');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "review_state" AS ENUM ('PUBLISHED', 'HIDDEN', 'REMOVED');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "review_language" AS ENUM ('EN', 'AR');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "review_report_reason" AS ENUM (
        'WRONG_BRANCH_OR_BUSINESS',
        'OFF_TOPIC_OR_SPAM',
        'HARASSMENT',
        'COMPETITOR_PROMOTION',
        'FAKE_NO_VISIT'
    );
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "review_report_status" AS ENUM ('OPEN', 'UPHELD', 'DISMISSED');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "invite_send_status" AS ENUM (
        'PENDING', 'SENT', 'RETRYING', 'UNKNOWN', 'FAILED', 'NO_CONTACT'
    );
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "rating_subject_type" AS ENUM ('STOREFRONT');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS "review_invite" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "storefront_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "booking_source" "booking_source" NOT NULL,
    "booking_id" UUID NOT NULL,
    -- SHA-256 OF THE TOKEN, never the token.
    "token_hash" TEXT NOT NULL,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "used_at" TIMESTAMPTZ(6),
    "customer_id" UUID,
    "salon_name" TEXT,
    "storefront_slug" TEXT,
    "locale" TEXT,
    "send_status" "invite_send_status" NOT NULL DEFAULT 'PENDING',
    "send_attempts" SMALLINT NOT NULL DEFAULT 0,
    "sent_at" TIMESTAMPTZ(6),
    "last_send_error" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "review_invite_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "review" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "storefront_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "booking_source" "booking_source" NOT NULL,
    "booking_id" UUID NOT NULL,
    "invite_id" UUID NOT NULL,
    "customer_id" UUID,
    "rating" SMALLINT NOT NULL,
    "comment" TEXT,
    "language" "review_language" NOT NULL,
    -- COPIED AT WRITE TIME, never joined. Stored as entered; a blank one is
    -- rendered as "Verified customer" at read time.
    "author_display_name" TEXT NOT NULL,
    "state" "review_state" NOT NULL DEFAULT 'PUBLISHED',
    "moderated_by_id" UUID,
    "moderated_at" TIMESTAMPTZ(6),
    "moderation_note" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "review_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "review_reply" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "review_id" UUID NOT NULL,
    "body" TEXT NOT NULL,
    -- RECORDED, NOT RENDERED: the public page says "Response from the salon".
    "author_id" UUID NOT NULL,
    "edited_by_id" UUID,
    "edited_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "review_reply_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "review_report" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "review_id" UUID NOT NULL,
    "reason" "review_report_reason" NOT NULL,
    "note" TEXT,
    "status" "review_report_status" NOT NULL DEFAULT 'OPEN',
    "reported_by_id" UUID NOT NULL,
    "resolved_by_id" UUID,
    "resolved_at" TIMESTAMPTZ(6),
    "resolution_note" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "review_report_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "rating_summary" (
    "subject_type" "rating_subject_type" NOT NULL,
    "subject_id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "review_count" INTEGER NOT NULL DEFAULT 0,
    "rating_sum" INTEGER NOT NULL DEFAULT 0,
    "star_1" INTEGER NOT NULL DEFAULT 0,
    "star_2" INTEGER NOT NULL DEFAULT 0,
    "star_3" INTEGER NOT NULL DEFAULT 0,
    "star_4" INTEGER NOT NULL DEFAULT 0,
    "star_5" INTEGER NOT NULL DEFAULT 0,
    "count_en" INTEGER NOT NULL DEFAULT 0,
    "count_ar" INTEGER NOT NULL DEFAULT 0,
    "version" BIGINT NOT NULL DEFAULT 0,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_recomputed_at" TIMESTAMPTZ(6),

    CONSTRAINT "rating_summary_pkey" PRIMARY KEY ("subject_type","subject_id")
);

-- ONE REVIEW PER BOOKING, EVER. Plain (not partial) because review has no
-- deleted_at: REMOVED is a state, so a removed review still holds its booking.
CREATE UNIQUE INDEX IF NOT EXISTS "review_booking_key"
    ON "review"("booking_source", "booking_id");
-- One review per invite.
CREATE UNIQUE INDEX IF NOT EXISTS "review_invite_id_key" ON "review"("invite_id");
CREATE INDEX IF NOT EXISTS "review_storefront_state_created_idx"
    ON "review"("storefront_id", "state", "created_at");
CREATE INDEX IF NOT EXISTS "review_tenant_branch_created_idx"
    ON "review"("tenant_id", "branch_id", "created_at");
CREATE INDEX IF NOT EXISTS "review_customer_idx" ON "review"("customer_id");

-- ONE REPLY PER REVIEW. Plain: replies are hard deleted, no dead rows.
CREATE UNIQUE INDEX IF NOT EXISTS "review_reply_review_id_key" ON "review_reply"("review_id");
CREATE INDEX IF NOT EXISTS "review_reply_tenant_idx" ON "review_reply"("tenant_id");

-- ONE INVITE PER BOOKING, EVER: a redelivered completion cannot mint twice.
CREATE UNIQUE INDEX IF NOT EXISTS "review_invite_booking_key"
    ON "review_invite"("booking_source", "booking_id");
CREATE UNIQUE INDEX IF NOT EXISTS "review_invite_token_hash_key" ON "review_invite"("token_hash");
CREATE INDEX IF NOT EXISTS "review_invite_expires_idx" ON "review_invite"("expires_at");
CREATE INDEX IF NOT EXISTS "review_invite_tenant_idx" ON "review_invite"("tenant_id");

-- The HQ queue: filter by status, oldest first.
CREATE INDEX IF NOT EXISTS "review_report_status_created_idx"
    ON "review_report"("status", "created_at");
CREATE INDEX IF NOT EXISTS "review_report_review_idx" ON "review_report"("review_id");
CREATE INDEX IF NOT EXISTS "review_report_tenant_idx" ON "review_report"("tenant_id");

CREATE INDEX IF NOT EXISTS "rating_summary_tenant_branch_idx"
    ON "rating_summary"("tenant_id", "branch_id");

-- RESTRICT: a review is the proof its invite was spent; the invite cannot go
-- while the review stands.
DO $$ BEGIN
    ALTER TABLE "review" ADD CONSTRAINT "review_invite_id_fkey"
        FOREIGN KEY ("invite_id") REFERENCES "review_invite"("id")
        ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- CASCADE: a reply or a complaint about a review that no longer exists is a
-- dangling row nobody can interpret (as the platform).
DO $$ BEGIN
    ALTER TABLE "review_reply" ADD CONSTRAINT "review_reply_review_id_fkey"
        FOREIGN KEY ("review_id") REFERENCES "review"("id")
        ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    ALTER TABLE "review_report" ADD CONSTRAINT "review_report_review_id_fkey"
        FOREIGN KEY ("review_id") REFERENCES "review"("id")
        ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- ─── hand-written: what Prisma cannot express ─────────────────────────────

-- ONE **OPEN** REPORT PER REVIEW. PARTIAL: resolved reports drop out of the
-- constraint, so history accumulates and a review dismissed in March can be
-- reported again in June, while one salon cannot file the same complaint
-- fifty times. Prisma cannot express a WHERE on an index, so this is the only
-- place it exists.
CREATE UNIQUE INDEX IF NOT EXISTS "review_report_one_open_per_review"
    ON "review_report"("review_id")
    WHERE "status" = 'OPEN';

-- review: the domain rules, as a backstop.
DO $$ BEGIN
    ALTER TABLE "review" ADD CONSTRAINT "review_rating_range"
        CHECK ("rating" BETWEEN 1 AND 5);
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- A comment is NULL or real text of at most 1000 characters. A blank comment
-- is stored as NULL, never as an empty or whitespace string.
DO $$ BEGIN
    ALTER TABLE "review" ADD CONSTRAINT "review_comment_shape"
        CHECK ("comment" IS NULL OR (char_length("comment") <= 1000 AND btrim("comment") <> ''));
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- At most 60 characters. Empty is allowed: it renders as "Verified customer".
DO $$ BEGIN
    ALTER TABLE "review" ADD CONSTRAINT "review_author_name_length"
        CHECK (char_length("author_display_name") <= 60);
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- A moderated review says who and when, together.
DO $$ BEGIN
    ALTER TABLE "review" ADD CONSTRAINT "review_moderation_stamp"
        CHECK (("moderated_by_id" IS NULL) = ("moderated_at" IS NULL));
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    ALTER TABLE "review_reply" ADD CONSTRAINT "review_reply_body_shape"
        CHECK (char_length("body") BETWEEN 1 AND 1500 AND btrim("body") <> '');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- review_invite: a SHA-256 hex digest and nothing else, so a plaintext token
-- (43 base64url characters) can never be written into this column by mistake.
DO $$ BEGIN
    ALTER TABLE "review_invite" ADD CONSTRAINT "review_invite_token_hash_is_sha256"
        CHECK ("token_hash" ~ '^[0-9a-f]{64}$');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    ALTER TABLE "review_invite" ADD CONSTRAINT "review_invite_expiry_after_creation"
        CHECK ("expires_at" > "created_at");
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    ALTER TABLE "review_invite" ADD CONSTRAINT "review_invite_sent_stamp"
        CHECK (("send_status" = 'SENT') = ("sent_at" IS NOT NULL));
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- review_report: the note caps, and an OPEN report has no resolution while a
-- decided one has all of it.
DO $$ BEGIN
    ALTER TABLE "review_report" ADD CONSTRAINT "review_report_note_length"
        CHECK ("note" IS NULL OR char_length("note") <= 500);
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    ALTER TABLE "review_report" ADD CONSTRAINT "review_report_resolution_shape"
        CHECK (
            ("status" = 'OPEN'
                AND "resolved_by_id" IS NULL AND "resolved_at" IS NULL AND "resolution_note" IS NULL)
            OR
            ("status" <> 'OPEN'
                AND "resolved_by_id" IS NOT NULL AND "resolved_at" IS NOT NULL
                AND char_length(btrim("resolution_note")) BETWEEN 10 AND 500)
        );
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- rating_summary: the counts must describe one consistent set of reviews.
-- The histogram and the language split are breakdowns of the count, and the
-- sum is what the histogram weighs. A drifted row fails loudly here instead of
-- printing a wrong star on a public page.
DO $$ BEGIN
    ALTER TABLE "rating_summary" ADD CONSTRAINT "rating_summary_consistent"
        CHECK (
            "review_count" >= 0
            AND "star_1" >= 0 AND "star_2" >= 0 AND "star_3" >= 0
            AND "star_4" >= 0 AND "star_5" >= 0
            AND "count_en" >= 0 AND "count_ar" >= 0
            AND "star_1" + "star_2" + "star_3" + "star_4" + "star_5" = "review_count"
            AND "count_en" + "count_ar" = "review_count"
            AND "rating_sum" = "star_1" + 2 * "star_2" + 3 * "star_3" + 4 * "star_4" + 5 * "star_5"
        );
EXCEPTION WHEN duplicate_object THEN null;
END $$;
